export const peopleList = [
  {
    id: "6062413c994a2121986da71f",
    age: 31,
    emoji: "🦄",
    eyeColor: "brown",
    name: "Kelli Castaneda",
    company: "DELPHIDE",
    email: "kellicastaneda@delphide.com",
    about:
      "Elit occaecat duis voluptate do fugiat do excepteur ipsum irure consectetur cupidatat officia ut. Deserunt nulla consectetur occaecat Lorem eu aliquip nostrud eiusmod nisi ad. Laborum ad nisi reprehenderit nostrud Lorem do veniam sint Lorem nulla. Aliqua est ex sit duis magna ullamco dolor excepteur velit do mollit duis ea esse. Nulla officia dolor in qui. Irure Lorem nisi pariatur sint do sint voluptate eiusmod sunt.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "6062413c23a10933d710c6a3",
    age: 40,
    emoji: "🚀",
    eyeColor: "blue",
    name: "Lakisha May",
    company: "VORTEXACO",
    email: "lakishamay@vortexaco.com",
    about:
      "Magna excepteur do ut laborum reprehenderit reprehenderit ullamco qui dolore id ad non. Est in minim occaecat in ut pariatur voluptate cupidatat ad excepteur consequat. Laboris qui ut elit ad aliqua ex cupidatat veniam. Voluptate ad irure sunt excepteur consectetur irure laborum labore eu irure nisi dolore veniam.\r\n",
    favoriteFruit: "banana",
  },
  {
    id: "6062413c28891767a0c506d7",
    age: 28,
    emoji: "😇",
    eyeColor: "blue",
    name: "Bruce Bauer",
    company: "COMTENT",
    email: "brucebauer@comtent.com",
    about:
      "Eiusmod excepteur nulla tempor laborum occaecat. Mollit magna pariatur sit excepteur. Quis voluptate officia sint irure Lorem ut occaecat labore voluptate enim aliquip. Sunt ullamco in amet laborum laboris.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "6062413c7c5038a1f2c87131",
    age: 22,
    emoji: "🦄",
    eyeColor: "blue",
    name: "Kemp Aguilar",
    company: "STEELTAB",
    email: "kempaguilar@steeltab.com",
    about:
      "Eu laboris ex amet proident sint duis. Proident veniam eu voluptate reprehenderit non labore non excepteur. Tempor laboris ea eu consectetur qui amet nulla nulla labore elit excepteur deserunt. Eiusmod eiusmod nisi reprehenderit aliquip esse.\r\n",
    favoriteFruit: "banana",
  },
  {
    id: "6062413c0c4a2e292ebde537",
    age: 25,
    emoji: "🥺",
    eyeColor: "green",
    name: "Casey Rivera",
    company: "LYRICHORD",
    email: "caseyrivera@lyrichord.com",
    about:
      "Est dolor cillum exercitation anim consequat aliqua amet Lorem sunt mollit consequat sunt nulla in. Magna eu amet eu ullamco ut dolor id. Nisi exercitation ipsum quis occaecat do enim culpa reprehenderit velit non. Pariatur id pariatur est cupidatat ipsum laborum anim exercitation do. Labore enim est elit esse enim tempor Lorem do labore. Nulla voluptate ut nisi aliqua voluptate est.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "606244f41d6501888bf10a85",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "green",
    name: "Sally Hodge",
    emoji: "😲",
    company: "MUSANPOLY",
    email: "sallyhodge@musanpoly.com",
    about:
      "Non veniam cupidatat sint aliquip magna est non dolor qui qui. Ex id laboris fugiat laborum laborum aliqua non minim in pariatur. Consequat ex irure non ullamco aliquip irure eiusmod. Adipisicing sit minim proident nostrud amet consectetur ea ut. Commodo proident eu mollit ea velit enim laborum duis in. Ex laboris voluptate pariatur nulla labore Lorem anim Lorem laboris anim mollit esse et Lorem. Velit mollit mollit excepteur irure ipsum ea minim voluptate sunt occaecat ea velit.\r\n",
    favoriteFruit: "apple",
  },
  {
    id: "606244f499b8028e67184e4e",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "blue",
    name: "Valencia Melendez",
    emoji: "🤪",
    company: "DOGNOSIS",
    email: "valenciamelendez@dognosis.com",
    about:
      "Tempor officia magna in commodo tempor labore voluptate tempor do sint. Pariatur aliquip pariatur ut eu eiusmod consequat. Dolore excepteur eiusmod ullamco cupidatat velit officia reprehenderit ea. Incididunt eiusmod commodo cillum sint sint veniam qui amet proident eiusmod ullamco ut.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "606244f4f7e4d6bb6257c004",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "green",
    name: "Phelps Tillman",
    emoji: "🙄",
    company: "BEZAL",
    email: "phelpstillman@bezal.com",
    about:
      "Lorem incididunt officia et exercitation commodo excepteur minim reprehenderit cupidatat aliqua mollit cillum. Velit reprehenderit ullamco exercitation do quis elit ipsum velit et ea elit. Est consequat officia fugiat ea irure excepteur. Do sunt officia tempor dolor occaecat commodo excepteur irure anim in labore cupidatat minim. Ipsum nulla tempor voluptate nulla ipsum consectetur do eiusmod pariatur. Sit eu elit aliqua reprehenderit veniam commodo duis fugiat excepteur in enim.\r\n",
    favoriteFruit: "banana",
  },
  {
    id: "606244f40c40d2cec3851515",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "blue",
    name: "Jacqueline Hendricks",
    emoji: "🧐",
    company: "BOVIS",
    email: "jacquelinehendricks@bovis.com",
    about:
      "Duis minim nulla pariatur ullamco. Commodo reprehenderit adipisicing elit cupidatat mollit. Nulla consectetur voluptate commodo aute duis minim aliquip consequat eiusmod ut.\r\n",
    favoriteFruit: "banana",
  },
  {
    id: "606244f40d2397a5d3a4e316",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "green",
    name: "Lila Howell",
    emoji: "🤓",
    company: "EARWAX",
    email: "lilahowell@earwax.com",
    about:
      "Veniam irure et do et ullamco est ea non veniam excepteur pariatur. Ea ut commodo duis ullamco cupidatat sint qui reprehenderit incididunt magna. Pariatur quis esse nisi elit aliqua et. Officia ipsum commodo consequat nostrud in do nisi pariatur enim excepteur officia eu exercitation. Est anim ex occaecat laborum aute.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "606244f4f53ba44960317072",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "brown",
    name: "Meredith Larson",
    emoji: "🥶",
    company: "RODEMCO",
    email: "meredithlarson@rodemco.com",
    about:
      "Excepteur ipsum et cupidatat sint ad occaecat nostrud ex officia. Irure duis eiusmod consectetur voluptate esse proident non. Commodo elit magna sunt qui. Voluptate amet elit magna elit ad deserunt culpa est non reprehenderit magna consectetur. In nisi proident dolor laborum sit nostrud duis. Est eu incididunt tempor aute sint qui commodo. Esse deserunt laboris in aute ullamco eu enim nulla tempor Lorem velit reprehenderit quis.\r\n",
    favoriteFruit: "banana",
  },
  {
    id: "606244f450db841daa1eec56",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Cox Hutchinson",
    emoji: "😎",
    company: "FARMAGE",
    email: "coxhutchinson@farmage.com",
    about:
      "Officia mollit deserunt tempor reprehenderit consectetur nisi. Aute proident est culpa aliqua laboris. Occaecat cupidatat aute ullamco aliqua velit veniam anim magna magna veniam Lorem dolore. Nulla veniam labore elit velit cupidatat veniam sit laborum est est labore eiusmod.\r\n",
    favoriteFruit: "strawberry",
  },
  {
    id: "606244f48db310bce303fa04",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Leblanc Mueller",
    emoji: "🥱",
    company: "UNQ",
    email: "leblancmueller@unq.com",
    about:
      "Anim nisi qui cillum veniam. Qui veniam minim nisi id incididunt ad consectetur consectetur minim. Eu reprehenderit aliqua incididunt ut ea incididunt non eu aute do aliquip tempor do sit.\r\n",
    favoriteFruit: "apple",
  },
  {
    id: "606244f487866e207b1c8e2c",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "brown",
    name: "Lorna Alvarez",
    emoji: "🤯",
    company: "APPLICA",
    email: "lornaalvarez@applica.com",
    about:
      "Amet enim magna velit eiusmod elit aute dolore labore ipsum Lorem est ex proident. Elit ullamco do ad ex ex elit fugiat non consequat tempor. Aute laboris reprehenderit id cupidatat. Sunt id veniam ad mollit excepteur velit esse.\r\n",
    favoriteFruit: "apple",
  },
];
